FROM python:3.10
RUN apt-get update && apt-get install -y \
    cmake \
    g++ \
    wget \
    libopenblas-dev \
    liblapack-dev \
    libx11-dev \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir protobuf==4.23.3 google-generativeai==0.8.5

EXPOSE 5000
CMD ["python", "app.py"]
